h = figure; plot(timevec, Smpl.ExctV(:,1))
hold on; plot(timevec, Smpl.InhbtV(:,1))
h = figure; plot(timevec, Smpl.ExctV(:,2))
hold on; plot(timevec, Smpl.InhbtV(:,2))
h = figure; plot(timevec, Smpl.WEI(:,1,1))
hold on; plot(timevec, Smpl.WEI(:,1,2))
hold on; plot(timevec, Smpl.WEI(:,2,1))
hold on; plot(timevec, Smpl.WEI(:,2,2))
h = figure; plot(timevec, Smpl.WIE(:,1,1))
hold on; plot(timevec, Smpl.WIE(:,1,2))
hold on; plot(timevec, Smpl.WIE(:,2,1))
hold on; plot(timevec, Smpl.WIE(:,2,2))