#!/bin/bash
#SBATCH --partition=v100
#SBATCH --job-name=ARRAY
#SBATCH --mem=120G
#SBATCH --time=7-00:00:00
#SBATCH --array=1-20
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --mail-type=END
#SBATCH --mail-user=bs3667@nyu.edu
cd ~/STDP
module purge
module load cuda/10.2.89
module load matlab/2021b
matlab -nodisplay -nosplash -r "run('MainNMDA1D.m'); exit;"

